spring:
  datasource:
    url: jdbc:mysql://localhost:3306/song_example?useSSL=false&characterEncoding=UTF-8&characterSetResults=UTF-8&serverTimezone=UTC
    username: testuser
    password: testpassword


  jpa:
    hibernate:
      ddl-auto: update
